# Generated by Django 3.1.3 on 2020-11-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('description', models.CharField(max_length=300, unique=True)),
                ('director', models.CharField(max_length=300, unique=True)),
                ('producer', models.CharField(max_length=300, unique=True)),
                ('release_date', models.CharField(max_length=300, unique=True)),
                ('rt_score', models.IntegerField(default=0)),
                ('species', models.CharField(max_length=300, unique=True)),
                ('url', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
