# Generated by Django 3.1.3 on 2020-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieId',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
