# Generated by Django 3.1.3 on 2020-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_auto_20201107_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='species',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
