# Generated by Django 3.1.3 on 2020-11-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_auto_20201107_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='species',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
    ]
