# Generated by Django 3.1.3 on 2020-11-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_auto_20201108_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='character',
        ),
    ]
