# Generated by Django 3.1.3 on 2020-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCharacter', '0002_auto_20201107_1537'),
        ('Movie', '0007_remove_movie_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='character',
            field=models.ManyToManyField(to='MovieCharacter.People'),
        ),
    ]
