# Generated by Django 3.1.3 on 2020-11-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleId', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('gender', models.CharField(max_length=300, unique=True)),
                ('age', models.CharField(max_length=300, unique=True)),
                ('eye_color', models.CharField(max_length=300, unique=True)),
                ('hair_color', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
