# Generated by Django 3.1.3 on 2020-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieCharacter', '0002_auto_20201107_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
